mode = "dark"

# Accent / UI
accent = "#98aacd"
hyprland_active_border = "#a4b7da"

# Selection
selection = "#98aacd"
selection_foreground = "#121212"

# Background ramp
background = "#121212"
dark_background = "#0e0e0e"
darker_background = "#090909"
lighter_background = "#1e1e1e"

# Foreground ramp
foreground = "#ffffff"
dark_foreground = "#9e9e9e"
light_foreground = "#ffffff"
bright_foreground = "#ffffff"

# Muted
muted = "#9e9e9e"

# Base colors
red = "#e08548"
green = "#cdcd98"
yellow = "#cdb598"
blue = "#98aacd"
magenta = "#bb98cd"
cyan = "#ffffff"

# Extra semantic colors
orange = "#e08548"
brown = "#704224"

# Bright colors
bright_red = "#f2b892"
bright_green = "#dadaa4"
bright_yellow = "#dac2a4"
bright_blue = "#a4b7da"
bright_magenta = "#c8a4da"
bright_cyan = "#d8e7f7"
